[sv 65588] Fix a buffer overrun in handling of .SHELLFLAGS.
A buffer overflow occurs in oneshell mode when shellflags contains characters
special to shell.

$ cat makefile
.ONESHELL:
.SHELLFLAGS:=hello'
all:;:
$ make
Aborted (core dumped)

In oneshell mode construct_command_argv_internal wants to store in argv[0]
the value of shell, followed by shellflags, followed by the command line.
construct_command_argv_internal preallocates memory with

nextp = new_argv[0] = xmalloc (shell_len + sflags_len + line_len + 3);

construct_command_argv_internal is then used recursively to construct argv from
shellflags.  If shellflags contains characters special to shell, then this
recursive call does the so-called slow mode and constructs argv of "/bin/sh",
"-c", and the value of shellflags.
One problem is that the top construct_command_argv_internal never allocated
room for the "/bin/sh" and "-c".

Aside from the overflow, it is incorrect to prepend "/bin/sh" and "-c" to
shellflags. Preallocaing more room in top construct_command_argv_internal can
solve the overflow, but the resultant command line stays incorrect, because
shellflags were not supposed to carry "/bin/sh" and "-c".

This commit parses shellflags without help from construct_command_argv_internal
and lets shellflags carry quoted tokens in oneshell mode, even when special
characters are present.

* src/job.c (construct_command_argv_internal): Fix a buffer overrun in
construct_command_argv_internal by using next_dequoted_token to parse
.SHELLFLAGS.
* src/token.h: Declare utilities to break up a C string to tokens.
* src/token.c: Implement utilities to break up a C string to tokens.
* src/token.t.c: Test the implementation in token.c.
* Makefile.am: Add token.h, token.c to make.
Add token.t.tsk as a check_PROGRAM.
Have rule 'check-regression' run token.t.tsk.
On test failure, once the makeerror tarball is ready, remove the temporary
directory that contains test logs.
* tests/scripts/variables/SHELLFLAGS: Add tests.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -37,7 +37,8 @@ make_SRCS =	src/ar.c src/arscan.c src/commands.c src/commands.h \
 		src/mkcustom.h src/os.h src/output.c src/output.h src/read.c \
 		src/remake.c src/rule.c src/rule.h src/shuffle.h src/shuffle.c \
 		src/signame.c src/strcache.c src/variable.c src/variable.h \
-		src/version.c src/vpath.c src/warning.c src/warning.h
+		src/version.c src/vpath.c src/warning.c src/warning.h \
+		src/token.c src/token.h
 
 w32_SRCS =	src/w32/pathstuff.c src/w32/w32os.c src/w32/compat/dirent.c \
 		src/w32/compat/posixfcn.c src/w32/include/dirent.h \
@@ -59,6 +60,8 @@ loadavg_SRCS =	lib/getloadavg.c
 
 make_SOURCES =	$(make_SRCS)
 EXTRA_make_SOURCES = $(vms_SRCS)
+check_PROGRAMS = token.t.tsk
+token_t_tsk_SOURCES = src/token.t.c
 
 if HAVE_GUILE
   _GUILE_CFLAGS = $(GUILE_CFLAGS)
@@ -126,7 +129,7 @@ EXTRA_DIST =	ChangeLog INSTALL README build.sh build.cfg.in $(man_MANS) \
 		README.W32 build_w32.bat src/config.h.W32 \
 		README.VMS makefile.com src/config.h-vms src/vmsjobs.c \
 		vms_export_symbol_test.com \
-		src/gmk-default.scm src/gmk-default.h \
+		src/gmk-default.scm src/gmk-default.h src/token.t.c \
 		$(mk_FILES) $(m4_FILES) $(test_FILES) $(w32_utf8_SRCS)
 
 # --------------- Generate the Guile default module content
@@ -171,43 +174,55 @@ MAKETESTFLAGS =
 GMK_OUTDIR = ..
 
 testlog = test-suite.log
+token_testlog = token_test.log
 testresult = tests/.test-result
+token_testresult = tests/.token_test-result
 errorpre = makeerror-$(PACKAGE_VERSION)-$(host_triplet)
 
-testfiles = $(testlog) $(testresult) $(errorfile)
+testfiles = $(testlog) $(token_testlog) $(testresult) $(token_testresult) $(errorfile)
 MOSTLYCLEANFILES = $(testfiles)
 
 errordetails =	config.status config.log src/config.h src/mkconfig.h \
-		$(testlog) tests/work
+		$(testlog) $(token_testlog)
 
 # Create a 4-letter random sequence
 rand_value = c = "abcdefghijklmnopqrstuvwxyz0123456789"
 rand_char  = substr(c,int(rand()*36),1)
 rand_string = $(AWK) 'BEGIN{srand(); $(rand_value); print $(rand_char) "" $(rand_char) "" $(rand_char) "" $(rand_char);}'
 
-check-regression: tests/config-flags.pm
+check-regression: token.t.tsk$(EXEEXT) tests/config-flags.pm
 	$(AM_V_at) rm -f $(testfiles)
+	$(AM_V_at) (./token.t.tsk$(EXEEXT); echo $$? >$(token_testresult)) 2>&1 | tee $(token_testlog)
 	$(AM_V_at) if test -f '$(top_srcdir)/tests/run_make_tests.pl'; then \
 	  ulimit -n 128; \
 	  if $(PERL) -v >/dev/null 2>&1; then \
 	    echo "cd tests && $(PERL) $(PERLFLAGS) $(abs_top_srcdir)/tests/run_make_tests.pl -make $(GMK_OUTDIR)/make$(EXEEXT) $(MAKETESTFLAGS)"; \
 	    (cd tests && $(PERL) $(PERLFLAGS) '$(abs_top_srcdir)/tests/run_make_tests.pl' -make '$(GMK_OUTDIR)/make$(EXEEXT)' $(MAKETESTFLAGS); echo $$? >.test-result) 2>&1 | tee $(testlog); \
-	    export TAR_OPTIONS='$(filter-out --sort%,$(TAR_OPTIONS))'; \
-	    er=$$(cat $(testresult)); if test "$$er" -ne 0; then \
-	      dirnm="$(errorpre)-$$($(rand_string))"; fnm="$$dirnm.tar.gz"; \
-	      rm -rf "$$dirnm"; mkdir "$$dirnm"; \
-	      $(AMTAR) chf - $(errordetails) | (cd "$$dirnm"; $(AMTAR) xf -); \
-	      $(AMTAR) chf - "$$dirnm" | eval GZIP= gzip $(GZIP_ENV) -c >"$$fnm"; \
-	      echo "*** Testing FAILED!  Details: $$fnm"; \
-	      echo '*** Please report to <$(PACKAGE_BUGREPORT)>'; echo; \
-	      exit $$er; \
-	    fi; \
 	  else \
 	    echo "Can't find a working Perl ($(PERL)); the test suite requires Perl."; \
 	  fi; \
 	else \
 	  echo "Can't find the $(PACKAGE_NAME) test suite ($(top_srcdir)/tests)."; \
 	fi
+	$(AM_V_at) \
+    export TAR_OPTIONS='$(filter-out --sort%,$(TAR_OPTIONS))'; \
+    er=$$(cat $(testresult)); \
+    if test "$$er" -eq 0; then \
+        errdetails='$(errordetails)'; \
+        er=$$(cat $(token_testresult)); \
+    else \
+        errdetails='$(errordetails) tests/work'; \
+    fi;\
+    if test "$$er" -ne 0; then \
+      dirnm="$(errorpre)-$$($(rand_string))"; fnm="$$dirnm.tar.gz"; \
+      rm -rf "$$dirnm"; mkdir "$$dirnm"; \
+      $(AMTAR) chf - $$errdetails | (cd "$$dirnm"; $(AMTAR) xf -); \
+      $(AMTAR) chf - "$$dirnm" | eval GZIP= gzip $(GZIP_ENV) -c >"$$fnm"; \
+      rm -r "$$dirnm"; \
+      echo "*** Testing FAILED!  Details: $$fnm"; \
+      echo '*** Please report to <$(PACKAGE_BUGREPORT)>'; echo; \
+      exit $$er; \
+    fi
 
 
 # --------------- Maintainer's Section
